const data = [
    {
        "createBy": "dinesh",
        "updateBy": "shriraam",
        "createdDt": "2021-12-01T05:07:21.000+0000",
        "updateDt": "2022-10-08T13:23:19.000+0000",
        "id": 357,
        "appCode": "ACT",
        "appName": "Automated Chaos Testing",
        "primaryManager": "Ramkumar Ramaselvan",
        "primaryManagerId": "ramkumar",
        "secondaryManager": "Shriraam Ravimathi",
        "secondaryManagerId": "shriraam",
        "businessUnit": "IT",
        "approvalGate": 1,
        "softDelete": false,
        "businessHead": "Bhuvaneshwaran Rangaraj",
        "businessHeadId": "bhuvaneshwaran"
    },
    {
        "createBy": "kevin",
        "updateBy": "shriraam",
        "createdDt": "2022-06-02T09:32:26.000+0000",
        "updateDt": "2022-10-08T13:25:49.000+0000",
        "id": 446,
        "appCode": "CODE8",
        "appName": "CODE8",
        "primaryManager": "Kevin Ramachandran",
        "primaryManagerId": "kevin",
        "secondaryManager": "Ramkumar Ramaselvan",
        "secondaryManagerId": "ramkumar",
        "businessUnit": "IT",
        "approvalGate": 1,
        "softDelete": false,
        "businessHead": "Sujai Narayanan",
        "businessHeadId": "sujai"
    },
    {
        "createBy": "kevin",
        "updateBy": "shriraam",
        "createdDt": "2022-01-17T07:38:21.000+0000",
        "updateDt": "2022-10-08T13:25:18.000+0000",
        "id": 396,
        "appCode": "DAAS",
        "appName": "DevOps as a Service",
        "primaryManager": "Sujai Narayanan",
        "primaryManagerId": "sujai",
        "secondaryManager": "Kevin Ramachandran",
        "secondaryManagerId": "kevin",
        "businessUnit": "IT",
        "approvalGate": 1,
        "softDelete": false,
        "businessHead": "cicd",
        "businessHeadId": "cicd"
    },
    {
        "createBy": "muralidharan",
        "updateBy": "shriraam",
        "createdDt": "2021-09-21T03:26:32.000+0000",
        "updateDt": "2022-10-08T13:26:32.000+0000",
        "id": 214,
        "appCode": "DOME",
        "appName": "DevOps Management Engine",
        "primaryManager": "Kevin Ramachandran",
        "primaryManagerId": "kevin",
        "secondaryManager": "Tushar Prasad",
        "secondaryManagerId": "tushar",
        "businessUnit": "IT DEP",
        "approvalGate": 1,
        "softDelete": false,
        "businessHead": "Bhuvaneshwaran Rangaraj",
        "businessHeadId": "bhuvaneshwaran"
    },
    {
        "createBy": "shriraam",
        "updateBy": "shriraam",
        "createdDt": "2022-10-08T13:24:31.000+0000",
        "updateDt": "2022-10-08T13:24:31.000+0000",
        "id": 491,
        "appCode": "AIFT",
        "appName": "Infosoft Technology Ltd",
        "primaryManager": "Tushar Prasad",
        "primaryManagerId": "tushar",
        "secondaryManager": "Sujai Narayanan",
        "secondaryManagerId": "sujai",
        "businessUnit": "IT",
        "approvalGate": 1,
        "softDelete": false,
        "businessHead": "Bhuvaneshwaran Rangaraj",
        "businessHeadId": "bhuvaneshwaran"
    },
    {
        "createBy": "shriraam",
        "updateBy": "shriraam",
        "createdDt": "2022-10-08T13:21:52.000+0000",
        "updateDt": "2022-10-08T13:21:52.000+0000",
        "id": 490,
        "appCode": "MAT",
        "appName": "Maturity Assessment",
        "primaryManager": "Sujai Narayanan",
        "primaryManagerId": "sujai",
        "secondaryManager": "Kevin Ramachandran",
        "secondaryManagerId": "kevin",
        "businessUnit": "IT",
        "approvalGate": 0,
        "softDelete": false,
        "businessHead": "Bhuvaneshwaran Rangaraj",
        "businessHeadId": "bhuvaneshwaran"
    },
    {
        "createBy": "dinesh",
        "updateBy": "lisha",
        "createdDt": "2021-09-21T10:44:19.000+0000",
        "updateDt": "2022-10-11T06:30:01.000+0000",
        "id": 221,
        "appCode": "PII",
        "appName": "Personal Identifiable Information",
        "primaryManager": "Kevin Ramachandran",
        "primaryManagerId": "kevin",
        "secondaryManager": "Bhuvaneshwaran Rangaraj",
        "secondaryManagerId": "bhuvaneshwaran",
        "businessUnit": "IT",
        "approvalGate": 0,
        "softDelete": false,
        "businessHead": "Jeevagan Sivakumar",
        "businessHeadId": "jeevagan"
    },
    {
        "createBy": "dinesh",
        "updateBy": "kevin",
        "createdDt": "2022-06-03T03:40:19.000+0000",
        "updateDt": "2022-10-10T08:44:53.000+0000",
        "id": 447,
        "appCode": "PROMOKART",
        "appName": "PROMOKART",
        "primaryManager": "Bhuvaneshwaran Rangaraj",
        "primaryManagerId": "bhuvaneshwaran",
        "secondaryManager": "Kevin Ramachandran",
        "secondaryManagerId": "kevin",
        "businessUnit": "IT",
        "approvalGate": 1,
        "softDelete": false,
        "businessHead": "Vignesh Ramankutty",
        "businessHeadId": "vignesh"
    }
]

module.exports = data;